// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:5026" | (string & {});
};

export type AuthResponseDto = {
    token: string | null;
    expiresAt?: string;
    user: UserDto;
};

export type BusAdminUpgradeRequestStatus = 0 | 1 | 2;

export type CreateBusAdminUpgradeRequestDto = {
    companyName: string;
    licenseNumber?: string | null;
    hotline?: string | null;
    reason?: string | null;
};

export type CreateBusDto = {
    busTypeID?: string;
    plateNumber?: string | null;
    isActive?: boolean;
};

export type CreateSeatLayoutDto = {
    seatLabel?: string | null;
    floor?: number;
    seatType?: SeatType;
    positionX?: number;
    positionY?: number;
};

export type CreateTripDto = {
    routeID?: string;
    busID?: string | null;
    busTypeID?: string;
    departureDate?: string;
    departureTime?: string;
    arrivalTime?: string;
    status?: TripStatus;
};

export type DistrictResponse = {
    id?: string | null;
    name?: string | null;
    wards?: Array<WardResponse> | null;
};

export type InforBusCompany = {
    name: string;
    licenseNumber?: string | null;
    hotline?: string | null;
};

export type LoginRequestDto = {
    email: string;
    password: string;
};

export type MePassengerDto = {
    passengerID?: string;
    fullName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
};

export type MeResponseDto = {
    passenger?: MePassengerDto;
    user?: MeUserInfoDto;
};

export type MeUserInfoDto = {
    userID?: string;
    email?: string | null;
    fullName?: string | null;
    phoneNumber?: string | null;
    isActive?: boolean;
    createdAt?: string;
    role?: MeUserRoleDto;
};

export type MeUserRoleDto = {
    roleID?: string;
    roleName?: string | null;
};

export type OAuthGoogleRequestDto = {
    idToken: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type ProvinceResponse = {
    id?: string | null;
    name?: string | null;
    districts?: Array<DistrictResponse> | null;
};

export type RegisterRequestDto = {
    email: string;
    password: string;
    fullName: string;
    phoneNumber?: string | null;
    identityCard?: string | null;
};

export type ReviewBusAdminUpgradeRequestDto = {
    approve: boolean;
    reviewNote?: string | null;
};

export type SeatType = 0 | 1 | 2 | 3 | 4 | 5;

export type TicketStatus = 0 | 1 | 2;

export type TripStatus = 0 | 1 | 2 | 3;

export type UpdateBusDto = {
    busTypeID?: string;
    plateNumber?: string | null;
    isActive?: boolean;
};

export type UpdateBusTypeAmenitiesDto = {
    amenities?: string | null;
};

export type UpdateCompanyProfileDto = {
    name?: string | null;
    licenseNumber?: string | null;
    hotline?: string | null;
};

export type UpdatePassengerDto = {
    fullName?: string | null;
    phoneNumber?: string | null;
    identityCard?: string | null;
};

export type UpdateSeatLayoutDto = {
    seatLabel?: string | null;
    floor?: number;
    seatType?: SeatType;
    positionX?: number;
    positionY?: number;
};

export type UpdateTripDto = {
    routeID?: string;
    busID?: string | null;
    busTypeID?: string;
    departureDate?: string;
    departureTime?: string;
    arrivalTime?: string;
    status?: TripStatus;
};

export type UserDto = {
    id?: string;
    email: string | null;
    fullName: string | null;
    phoneNumber: string | null;
    role: string | null;
    isActive?: boolean;
};

export type WardResponse = {
    id?: string | null;
    name?: string | null;
};

export type PostApiAuthOauthGoogleData = {
    body?: OAuthGoogleRequestDto;
    path?: never;
    query?: never;
    url: "/api/auth/oauth/google";
};

export type PostApiAuthOauthGoogleResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthOauthGoogleResponse = PostApiAuthOauthGoogleResponses[keyof PostApiAuthOauthGoogleResponses];

export type PostApiAuthLoginData = {
    body?: LoginRequestDto;
    path?: never;
    query?: never;
    url: "/api/auth/login";
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body?: RegisterRequestDto;
    path?: never;
    query?: never;
    url: "/api/auth/register";
};

export type PostApiAuthRegisterResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiBusadminBusesData = {
    body?: CreateBusDto;
    path?: never;
    query?: never;
    url: "/api/busadmin/buses";
};

export type PostApiBusadminBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/busadmin/buses/{id}";
};

export type DeleteApiBusadminBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesByIdData = {
    body?: UpdateBusDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/busadmin/buses/{id}";
};

export type PutApiBusadminBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesTripsData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: "/api/busadmin/buses/trips";
};

export type GetApiBusadminBusesTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBusadminBusesTripsData = {
    body?: CreateTripDto;
    path?: never;
    query?: never;
    url: "/api/busadmin/buses/trips";
};

export type PostApiBusadminBusesTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesTripsByTripIdData = {
    body?: never;
    path: {
        tripId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/trips/{tripId}";
};

export type DeleteApiBusadminBusesTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesTripsByTripIdData = {
    body?: UpdateTripDto;
    path: {
        tripId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/trips/{tripId}";
};

export type PutApiBusadminBusesTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/bus-types/{busTypeId}/seat-layouts";
};

export type GetApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsData = {
    body?: CreateSeatLayoutDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/bus-types/{busTypeId}/seat-layouts";
};

export type PostApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesSeatLayoutsByLayoutIdData = {
    body?: never;
    path: {
        layoutId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/seat-layouts/{layoutId}";
};

export type DeleteApiBusadminBusesSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesSeatLayoutsByLayoutIdData = {
    body?: UpdateSeatLayoutDto;
    path: {
        layoutId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/seat-layouts/{layoutId}";
};

export type PutApiBusadminBusesSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesCompanyData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/busadmin/buses/company";
};

export type GetApiBusadminBusesCompanyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesCompanyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/busadmin/buses/company/profile";
};

export type GetApiBusadminBusesCompanyProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesCompanyProfileData = {
    body?: UpdateCompanyProfileDto;
    path?: never;
    query?: never;
    url: "/api/busadmin/buses/company/profile";
};

export type PutApiBusadminBusesCompanyProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: TicketStatus;
    };
    url: "/api/busadmin/buses/tickets";
};

export type GetApiBusadminBusesTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesBusTypesByBusTypeIdAmenitiesData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/bus-types/{busTypeId}/amenities";
};

export type GetApiBusadminBusesBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiBusadminBusesBusTypesByBusTypeIdAmenitiesData = {
    body?: UpdateBusTypeAmenitiesDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/busadmin/buses/bus-types/{busTypeId}/amenities";
};

export type PatchApiBusadminBusesBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesStatsMonthlyData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: "/api/busadmin/buses/stats/monthly";
};

export type GetApiBusadminBusesStatsMonthlyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAddBusCompanyData = {
    body?: InforBusCompany;
    path?: never;
    query?: never;
    url: "/addBusCompany";
};

export type PostAddBusCompanyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiPassengerUpgradeRequestsBusadminData = {
    body?: CreateBusAdminUpgradeRequestDto;
    path?: never;
    query?: never;
    url: "/api/passenger/upgrade-requests/busadmin";
};

export type PostApiPassengerUpgradeRequestsBusadminResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPassengerProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/passenger/profile";
};

export type GetApiPassengerProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiPassengerProfileData = {
    body?: UpdatePassengerDto;
    path?: never;
    query?: never;
    url: "/api/passenger/profile";
};

export type PutApiPassengerProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPassengerTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/passenger/tickets";
};

export type GetApiPassengerTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/ping";
};

export type GetApiPingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLandingProvincesSearchData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: "/api/landing/provinces/search";
};

export type GetApiLandingProvincesSearchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetApiLandingProvincesSearchError =
    GetApiLandingProvincesSearchErrors[keyof GetApiLandingProvincesSearchErrors];

export type GetApiLandingProvincesSearchResponses = {
    /**
     * OK
     */
    200: Array<ProvinceResponse>;
};

export type GetApiLandingProvincesSearchResponse =
    GetApiLandingProvincesSearchResponses[keyof GetApiLandingProvincesSearchResponses];

export type GetApiAdminBusAdminUpgradeRequestsData = {
    body?: never;
    path?: never;
    query?: {
        status?: BusAdminUpgradeRequestStatus;
    };
    url: "/api/admin/bus-admin-upgrade-requests";
};

export type GetApiAdminBusAdminUpgradeRequestsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiAdminBusAdminUpgradeRequestsByRequestIdReviewData = {
    body?: ReviewBusAdminUpgradeRequestDto;
    path: {
        requestId: string;
    };
    query?: never;
    url: "/api/admin/bus-admin-upgrade-requests/{requestId}/review";
};

export type PatchApiAdminBusAdminUpgradeRequestsByRequestIdReviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdBusesData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: "/api/admin/system/companies/{companyId}/buses";
};

export type GetApiAdminSystemCompaniesByCompanyIdBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemCompaniesByCompanyIdBusesData = {
    body?: CreateBusDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: "/api/admin/system/companies/{companyId}/buses";
};

export type PostApiAdminSystemCompaniesByCompanyIdBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemBusesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/admin/system/buses/{id}";
};

export type DeleteApiAdminSystemBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemBusesByIdData = {
    body?: UpdateBusDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/admin/system/buses/{id}";
};

export type PutApiAdminSystemBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdTripsData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: {
        year?: number;
        month?: number;
    };
    url: "/api/admin/system/companies/{companyId}/trips";
};

export type GetApiAdminSystemCompaniesByCompanyIdTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemCompaniesByCompanyIdTripsData = {
    body?: CreateTripDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: "/api/admin/system/companies/{companyId}/trips";
};

export type PostApiAdminSystemCompaniesByCompanyIdTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemTripsByTripIdData = {
    body?: never;
    path: {
        tripId: string;
    };
    query?: never;
    url: "/api/admin/system/trips/{tripId}";
};

export type DeleteApiAdminSystemTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemTripsByTripIdData = {
    body?: UpdateTripDto;
    path: {
        tripId: string;
    };
    query?: never;
    url: "/api/admin/system/trips/{tripId}";
};

export type PutApiAdminSystemTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemBusTypesByBusTypeIdSeatLayoutsData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/admin/system/bus-types/{busTypeId}/seat-layouts";
};

export type GetApiAdminSystemBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemBusTypesByBusTypeIdSeatLayoutsData = {
    body?: CreateSeatLayoutDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/admin/system/bus-types/{busTypeId}/seat-layouts";
};

export type PostApiAdminSystemBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemSeatLayoutsByLayoutIdData = {
    body?: never;
    path: {
        layoutId: string;
    };
    query?: never;
    url: "/api/admin/system/seat-layouts/{layoutId}";
};

export type DeleteApiAdminSystemSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemSeatLayoutsByLayoutIdData = {
    body?: UpdateSeatLayoutDto;
    path: {
        layoutId: string;
    };
    query?: never;
    url: "/api/admin/system/seat-layouts/{layoutId}";
};

export type PutApiAdminSystemSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
    };
    url: "/api/admin/system/companies";
};

export type GetApiAdminSystemCompaniesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdProfileData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: "/api/admin/system/companies/{companyId}/profile";
};

export type GetApiAdminSystemCompaniesByCompanyIdProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemCompaniesByCompanyIdProfileData = {
    body?: UpdateCompanyProfileDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: "/api/admin/system/companies/{companyId}/profile";
};

export type PutApiAdminSystemCompaniesByCompanyIdProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdTicketsData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: {
        status?: TicketStatus;
    };
    url: "/api/admin/system/companies/{companyId}/tickets";
};

export type GetApiAdminSystemCompaniesByCompanyIdTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemBusTypesByBusTypeIdAmenitiesData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/admin/system/bus-types/{busTypeId}/amenities";
};

export type GetApiAdminSystemBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiAdminSystemBusTypesByBusTypeIdAmenitiesData = {
    body?: UpdateBusTypeAmenitiesDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: "/api/admin/system/bus-types/{busTypeId}/amenities";
};

export type PatchApiAdminSystemBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemUsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: "/api/admin/system/users/{userId}";
};

export type GetApiAdminSystemUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemUsersByUserIdTicketsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: "/api/admin/system/users/{userId}/tickets";
};

export type GetApiAdminSystemUsersByUserIdTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemStatsMonthlyData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: "/api/admin/system/stats/monthly";
};

export type GetApiAdminSystemStatsMonthlyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/user/me";
};

export type GetApiUserMeResponses = {
    /**
     * OK
     */
    200: MeResponseDto;
};

export type GetApiUserMeResponse = GetApiUserMeResponses[keyof GetApiUserMeResponses];

export type GetApiUserMeTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/user/me/tickets";
};

export type GetApiUserMeTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};
