// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5026' | (string & {});
};

export type AdminCreateUserDto = {
    email: string;
    password: string;
    fullName: string;
    phoneNumber?: string | null;
    role: string;
    isActive?: boolean;
};

export type AdminDashboardDailyStatDto = {
    date?: string | null;
    label?: string | null;
    soldTickets?: number;
    cancelledTickets?: number;
    revenue?: number;
};

export type AdminDashboardKpiDto = {
    current?: number;
    previous?: number;
    delta?: number;
    deltaPercent?: number;
};

export type AdminDashboardMonthlyStatDto = {
    label?: string | null;
    monthKey?: string | null;
    revenue?: number;
    soldTickets?: number;
};

export type AdminDashboardOverviewDto = {
    currentMonthLabel?: string | null;
    lastUpdatedAt?: string;
    revenue?: AdminDashboardKpiDto;
    soldTickets?: AdminDashboardKpiDto;
    totalTrips?: AdminDashboardKpiDto;
    newUsers?: AdminDashboardKpiDto;
    snapshot?: AdminDashboardSnapshotDto;
    monthlyStats?: Array<AdminDashboardMonthlyStatDto> | null;
    dailyStats?: Array<AdminDashboardDailyStatDto> | null;
    topRoutes?: Array<AdminDashboardTopRouteDto> | null;
    recentBookings?: Array<AdminDashboardRecentBookingDto> | null;
    ticketStatusBreakdown?: Array<AdminDashboardStatusStatDto> | null;
    upgradeRequestBreakdown?: Array<AdminDashboardStatusStatDto> | null;
};

export type AdminDashboardRecentBookingDto = {
    bookingId?: string;
    contactName?: string | null;
    contactEmail?: string | null;
    totalAmount?: number;
    ticketCount?: number;
    routeName?: string | null;
    status?: string | null;
    createdAt?: string;
};

export type AdminDashboardSnapshotDto = {
    totalUsers?: number;
    totalCompanies?: number;
    approvedCompanies?: number;
    totalRoutes?: number;
    activeTripsToday?: number;
    totalTripsThisMonth?: number;
    pendingUpgradeRequests?: number;
    cancellationRatePercent?: number;
    averageTicketPrice?: number;
};

export type AdminDashboardStatusStatDto = {
    label?: string | null;
    value?: number;
};

export type AdminDashboardTopRouteDto = {
    routeName?: string | null;
    ticketsSold?: number;
    revenue?: number;
};

export type AdminUpdateUserDto = {
    email: string;
    fullName: string;
    phoneNumber?: string | null;
    role: string;
    isActive?: boolean;
};

export type AmenityDto = {
    amenityId?: string;
    name?: string | null;
    description?: string | null;
    iconName?: string | null;
    category?: string | null;
};

export type AuthResponseDto = {
    token: string | null;
    expiresAt?: string;
    user: UserDto;
};

export type BusAdminUpgradeRequestStatus = 0 | 1 | 2;

export type CreateBusAdminUpgradeRequestDto = {
    companyName: string;
    licenseNumber?: string | null;
    hotline?: string | null;
    reason?: string | null;
};

export type CreateBusDto = {
    busTypeID?: string;
    plateNumber?: string | null;
    isActive?: boolean;
};

export type CreateSeatLayoutDto = {
    seatLabel?: string | null;
    floor?: number;
    seatType?: SeatType;
    positionX?: number;
    positionY?: number;
};

export type CreateTripDto = {
    routeID?: string;
    busID?: string | null;
    busTypeID?: string;
    departureDate?: string;
    departureTime?: string;
    arrivalTime?: string;
    status?: TripStatus;
};

export type DistrictResponse = {
    id?: string | null;
    name?: string | null;
    name_en?: string | null;
    wards?: Array<WardResponse> | null;
};

export type InforBusCompany = {
    name: string;
    licenseNumber?: string | null;
    hotline?: string | null;
};

export type LoginRequestDto = {
    email: string;
    password: string;
};

export type MePassengerDto = {
    passengerID?: string;
    fullName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
};

export type MeResponseDto = {
    passenger?: MePassengerDto;
    user?: MeUserInfoDto;
};

export type MeUserInfoDto = {
    userID?: string;
    email?: string | null;
    fullName?: string | null;
    phoneNumber?: string | null;
    isActive?: boolean;
    createdAt?: string;
    role?: MeUserRoleDto;
};

export type MeUserRoleDto = {
    roleID?: string;
    roleName?: string | null;
};

export type OAuthGoogleRequestDto = {
    idToken: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type ProvinceResponse = {
    id?: string | null;
    name?: string | null;
    name_en?: string | null;
    districts?: Array<DistrictResponse> | null;
};

export type RegisterRequestDto = {
    email: string;
    password: string;
    fullName: string;
    phoneNumber?: string | null;
    identityCard?: string | null;
};

export type ReviewBusAdminUpgradeRequestDto = {
    approve: boolean;
    reviewNote?: string | null;
};

export type SeatType = 0 | 1 | 2 | 3 | 4 | 5;

export type TicketStatus = 0 | 1 | 2;

export type TimeRangeFilter = 1 | 2 | 3 | 4;

export type TripDetailDto = {
    tripId?: string;
    routeId?: string;
    companyId?: string;
    busCompanyName?: string | null;
    busTypeName?: string | null;
    busTypeDescription?: string | null;
    routeName?: string | null;
    departureDate?: string;
    departureTime?: string;
    arrivalTime?: string;
    durationMinutes?: number;
    totalSeats?: number;
    availableSeats?: number;
    lowestPrice?: number;
    rating?: number;
    reviewCount?: number;
    amenities?: Array<AmenityDto> | null;
    images?: Array<string> | null;
    pickupStops?: Array<TripDetailRouteStopDto> | null;
    dropoffStops?: Array<TripDetailRouteStopDto> | null;
    cancellationPolicy?: string | null;
    notes?: string | null;
};

export type TripDetailRouteStopDto = {
    stationId?: string;
    stationName?: string | null;
    provinceCode?: string | null;
    districtCode?: string | null;
    wardCode?: string | null;
    addressDetail?: string | null;
    stopOrder?: number;
    isPickUp?: boolean;
    isDropOff?: boolean;
    durationFromStart?: number;
};

export type TripRouteStopDto = {
    stationId?: string;
    stationName?: string | null;
    stopOrder?: number;
    isPickUp?: boolean;
    isDropOff?: boolean;
    durationFromStart?: number;
};

export type TripSearchAmenityFilterOptionDto = {
    amenity?: AmenityDto;
    count?: number;
};

export type TripSearchCompanyFilterOptionDto = {
    companyId?: string;
    name?: string | null;
    count?: number;
};

export type TripSearchFilterMetadataDto = {
    busCompanies?: Array<TripSearchCompanyFilterOptionDto> | null;
    departureTimeRanges?: Array<TripSearchTimeRangeFilterOptionDto> | null;
    amenities?: Array<TripSearchAmenityFilterOptionDto> | null;
    priceRange?: TripSearchPriceRangeDto;
};

export type TripSearchItemDto = {
    tripId?: string;
    routeId?: string;
    companyId?: string;
    busCompanyName?: string | null;
    busTypeName?: string | null;
    routeName?: string | null;
    departureLocation?: string | null;
    arrivalLocation?: string | null;
    departureTime?: string;
    arrivalTime?: string;
    durationMinutes?: number;
    lowestPrice?: number;
    availableSeats?: number;
    rating?: number;
    reviewCount?: number;
    amenities?: Array<AmenityDto> | null;
    imageUrl?: string | null;
    pickupStops?: Array<TripRouteStopDto> | null;
    dropoffStops?: Array<TripRouteStopDto> | null;
};

export type TripSearchLocationSummaryDto = {
    provinceCode?: string | null;
    districtCode?: string | null;
    wardCode?: string | null;
    displayName?: string | null;
};

export type TripSearchPriceRangeDto = {
    min?: number;
    max?: number;
};

export type TripSearchResult = {
    totalResults?: number;
    page?: number;
    pageSize?: number;
    summary?: TripSearchSummaryDto;
    filters?: TripSearchFilterMetadataDto;
    items?: Array<TripSearchItemDto> | null;
};

export type TripSearchSummaryDto = {
    origin?: TripSearchLocationSummaryDto;
    destination?: TripSearchLocationSummaryDto;
    departureDate?: string;
};

export type TripSearchTimeRangeFilterOptionDto = {
    value?: TimeRangeFilter;
    count?: number;
};

export type TripSortBy = 0 | 1 | 2 | 3 | 4 | 5;

export type TripStatus = 0 | 1 | 2 | 3;

export type UpdateBusDto = {
    busTypeID?: string;
    plateNumber?: string | null;
    isActive?: boolean;
};

export type UpdateBusTypeAmenitiesDto = {
    amenities?: string | null;
};

export type UpdateCompanyProfileDto = {
    name?: string | null;
    licenseNumber?: string | null;
    hotline?: string | null;
};

export type UpdatePassengerDto = {
    fullName?: string | null;
    phoneNumber?: string | null;
    identityCard?: string | null;
};

export type UpdateSeatLayoutDto = {
    seatLabel?: string | null;
    floor?: number;
    seatType?: SeatType;
    positionX?: number;
    positionY?: number;
};

export type UpdateTripDto = {
    routeID?: string;
    busID?: string | null;
    busTypeID?: string;
    departureDate?: string;
    departureTime?: string;
    arrivalTime?: string;
    status?: TripStatus;
};

export type UserDto = {
    id?: string;
    email: string | null;
    fullName: string | null;
    phoneNumber: string | null;
    role: string | null;
    isActive?: boolean;
};

export type WardResponse = {
    id?: string | null;
    name?: string | null;
    name_en?: string | null;
};

export type PostApiAuthOauthGoogleData = {
    body?: OAuthGoogleRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/oauth/google';
};

export type PostApiAuthOauthGoogleResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthOauthGoogleResponse = PostApiAuthOauthGoogleResponses[keyof PostApiAuthOauthGoogleResponses];

export type PostApiAuthLoginData = {
    body?: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body?: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * OK
     */
    200: AuthResponseDto;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiBusadminBusesData = {
    body?: CreateBusDto;
    path?: never;
    query?: never;
    url: '/api/busadmin/buses';
};

export type PostApiBusadminBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/busadmin/buses/{id}';
};

export type DeleteApiBusadminBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesByIdData = {
    body?: UpdateBusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/busadmin/buses/{id}';
};

export type PutApiBusadminBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesTripsData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
        page?: number;
        pageSize?: number;
    };
    url: '/api/busadmin/buses/trips';
};

export type GetApiBusadminBusesTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBusadminBusesTripsData = {
    body?: CreateTripDto;
    path?: never;
    query?: never;
    url: '/api/busadmin/buses/trips';
};

export type PostApiBusadminBusesTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesTripsByTripIdData = {
    body?: never;
    path: {
        tripId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/trips/{tripId}';
};

export type DeleteApiBusadminBusesTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesTripsByTripIdData = {
    body?: UpdateTripDto;
    path: {
        tripId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/trips/{tripId}';
};

export type PutApiBusadminBusesTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/busadmin/buses/bus-types/{busTypeId}/seat-layouts';
};

export type GetApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsData = {
    body?: CreateSeatLayoutDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/bus-types/{busTypeId}/seat-layouts';
};

export type PostApiBusadminBusesBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiBusadminBusesSeatLayoutsByLayoutIdData = {
    body?: never;
    path: {
        layoutId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/seat-layouts/{layoutId}';
};

export type DeleteApiBusadminBusesSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesSeatLayoutsByLayoutIdData = {
    body?: UpdateSeatLayoutDto;
    path: {
        layoutId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/seat-layouts/{layoutId}';
};

export type PutApiBusadminBusesSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesCompanyData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/api/busadmin/buses/company';
};

export type GetApiBusadminBusesCompanyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesCompanyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/busadmin/buses/company/profile';
};

export type GetApiBusadminBusesCompanyProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiBusadminBusesCompanyProfileData = {
    body?: UpdateCompanyProfileDto;
    path?: never;
    query?: never;
    url: '/api/busadmin/buses/company/profile';
};

export type PutApiBusadminBusesCompanyProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: TicketStatus;
        page?: number;
        pageSize?: number;
    };
    url: '/api/busadmin/buses/tickets';
};

export type GetApiBusadminBusesTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesBusTypesByBusTypeIdAmenitiesData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/bus-types/{busTypeId}/amenities';
};

export type GetApiBusadminBusesBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiBusadminBusesBusTypesByBusTypeIdAmenitiesData = {
    body?: UpdateBusTypeAmenitiesDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/busadmin/buses/bus-types/{busTypeId}/amenities';
};

export type PatchApiBusadminBusesBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBusadminBusesStatsMonthlyData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: '/api/busadmin/buses/stats/monthly';
};

export type GetApiBusadminBusesStatsMonthlyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBusadminAddBusCompanyData = {
    body?: InforBusCompany;
    path?: never;
    query?: never;
    url: '/api/busadmin/addBusCompany';
};

export type PostApiBusadminAddBusCompanyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiPassengerUpgradeRequestsBusadminData = {
    body?: CreateBusAdminUpgradeRequestDto;
    path?: never;
    query?: never;
    url: '/api/passenger/upgrade-requests/busadmin';
};

export type PostApiPassengerUpgradeRequestsBusadminResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPassengerProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/passenger/profile';
};

export type GetApiPassengerProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiPassengerProfileData = {
    body?: UpdatePassengerDto;
    path?: never;
    query?: never;
    url: '/api/passenger/profile';
};

export type PutApiPassengerProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPassengerTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/passenger/tickets';
};

export type GetApiPassengerTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLandingProvincesSearchData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: '/api/landing/provinces/search';
};

export type GetApiLandingProvincesSearchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetApiLandingProvincesSearchError = GetApiLandingProvincesSearchErrors[keyof GetApiLandingProvincesSearchErrors];

export type GetApiLandingProvincesSearchResponses = {
    /**
     * OK
     */
    200: Array<ProvinceResponse>;
};

export type GetApiLandingProvincesSearchResponse = GetApiLandingProvincesSearchResponses[keyof GetApiLandingProvincesSearchResponses];

export type GetApiTripsSearchData = {
    body?: never;
    path?: never;
    query: {
        FromProvinceCode: string;
        FromDistrictCode?: string;
        FromWardCode?: string;
        ToProvinceCode: string;
        ToDistrictCode?: string;
        ToWardCode?: string;
        DepartureDate: string;
        SortBy?: TripSortBy;
        DepartureTimeRanges?: Array<TimeRangeFilter>;
        BusCompanyIds?: Array<string>;
        MinPrice?: number;
        MaxPrice?: number;
        AmenityIds?: Array<string>;
        Page?: number;
        PageSize?: number;
    };
    url: '/api/trips/search';
};

export type GetApiTripsSearchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetApiTripsSearchError = GetApiTripsSearchErrors[keyof GetApiTripsSearchErrors];

export type GetApiTripsSearchResponses = {
    /**
     * OK
     */
    200: TripSearchResult;
};

export type GetApiTripsSearchResponse = GetApiTripsSearchResponses[keyof GetApiTripsSearchResponses];

export type GetApiAdminBusAdminUpgradeRequestsData = {
    body?: never;
    path?: never;
    query?: {
        status?: BusAdminUpgradeRequestStatus;
        page?: number;
        pageSize?: number;
    };
    url: '/api/admin/bus-admin-upgrade-requests';
};

export type GetApiAdminBusAdminUpgradeRequestsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiAdminBusAdminUpgradeRequestsByRequestIdReviewData = {
    body?: ReviewBusAdminUpgradeRequestDto;
    path: {
        requestId: string;
    };
    query?: never;
    url: '/api/admin/bus-admin-upgrade-requests/{requestId}/review';
};

export type PatchApiAdminBusAdminUpgradeRequestsByRequestIdReviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdBusesData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/admin/system/companies/{companyId}/buses';
};

export type GetApiAdminSystemCompaniesByCompanyIdBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemCompaniesByCompanyIdBusesData = {
    body?: CreateBusDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/admin/system/companies/{companyId}/buses';
};

export type PostApiAdminSystemCompaniesByCompanyIdBusesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemBusesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/system/buses/{id}';
};

export type DeleteApiAdminSystemBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemBusesByIdData = {
    body?: UpdateBusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/system/buses/{id}';
};

export type PutApiAdminSystemBusesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdTripsData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: {
        year?: number;
        month?: number;
        page?: number;
        pageSize?: number;
    };
    url: '/api/admin/system/companies/{companyId}/trips';
};

export type GetApiAdminSystemCompaniesByCompanyIdTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemCompaniesByCompanyIdTripsData = {
    body?: CreateTripDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/admin/system/companies/{companyId}/trips';
};

export type PostApiAdminSystemCompaniesByCompanyIdTripsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemTripsByTripIdData = {
    body?: never;
    path: {
        tripId: string;
    };
    query?: never;
    url: '/api/admin/system/trips/{tripId}';
};

export type DeleteApiAdminSystemTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemTripsByTripIdData = {
    body?: UpdateTripDto;
    path: {
        tripId: string;
    };
    query?: never;
    url: '/api/admin/system/trips/{tripId}';
};

export type PutApiAdminSystemTripsByTripIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemBusTypesByBusTypeIdSeatLayoutsData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/admin/system/bus-types/{busTypeId}/seat-layouts';
};

export type GetApiAdminSystemBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemBusTypesByBusTypeIdSeatLayoutsData = {
    body?: CreateSeatLayoutDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/admin/system/bus-types/{busTypeId}/seat-layouts';
};

export type PostApiAdminSystemBusTypesByBusTypeIdSeatLayoutsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemSeatLayoutsByLayoutIdData = {
    body?: never;
    path: {
        layoutId: string;
    };
    query?: never;
    url: '/api/admin/system/seat-layouts/{layoutId}';
};

export type DeleteApiAdminSystemSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemSeatLayoutsByLayoutIdData = {
    body?: UpdateSeatLayoutDto;
    path: {
        layoutId: string;
    };
    query?: never;
    url: '/api/admin/system/seat-layouts/{layoutId}';
};

export type PutApiAdminSystemSeatLayoutsByLayoutIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/admin/system/companies';
};

export type GetApiAdminSystemCompaniesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdProfileData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/admin/system/companies/{companyId}/profile';
};

export type GetApiAdminSystemCompaniesByCompanyIdProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemCompaniesByCompanyIdProfileData = {
    body?: UpdateCompanyProfileDto;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/api/admin/system/companies/{companyId}/profile';
};

export type PutApiAdminSystemCompaniesByCompanyIdProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemCompaniesByCompanyIdTicketsData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: {
        status?: TicketStatus;
        page?: number;
        pageSize?: number;
    };
    url: '/api/admin/system/companies/{companyId}/tickets';
};

export type GetApiAdminSystemCompaniesByCompanyIdTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemBusTypesByBusTypeIdAmenitiesData = {
    body?: never;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/admin/system/bus-types/{busTypeId}/amenities';
};

export type GetApiAdminSystemBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiAdminSystemBusTypesByBusTypeIdAmenitiesData = {
    body?: UpdateBusTypeAmenitiesDto;
    path: {
        busTypeId: string;
    };
    query?: never;
    url: '/api/admin/system/bus-types/{busTypeId}/amenities';
};

export type PatchApiAdminSystemBusTypesByBusTypeIdAmenitiesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAdminSystemUsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/admin/system/users/{userId}';
};

export type DeleteApiAdminSystemUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemUsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/admin/system/users/{userId}';
};

export type GetApiAdminSystemUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiAdminSystemUsersByUserIdData = {
    body?: AdminUpdateUserDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/admin/system/users/{userId}';
};

export type PutApiAdminSystemUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemUsersByUserIdTicketsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/admin/system/users/{userId}/tickets';
};

export type GetApiAdminSystemUsersByUserIdTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemStatsMonthlyData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: '/api/admin/system/stats/monthly';
};

export type GetApiAdminSystemStatsMonthlyResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAdminSystemDashboardOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/system/dashboard/overview';
};

export type GetApiAdminSystemDashboardOverviewResponses = {
    /**
     * OK
     */
    200: AdminDashboardOverviewDto;
};

export type GetApiAdminSystemDashboardOverviewResponse = GetApiAdminSystemDashboardOverviewResponses[keyof GetApiAdminSystemDashboardOverviewResponses];

export type GetApiAdminSystemUsersData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        roles?: Array<string>;
        statuses?: Array<string>;
        role?: string;
        isActive?: boolean;
        sortBy?: string;
        sortDirection?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/admin/system/users';
};

export type GetApiAdminSystemUsersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAdminSystemUsersData = {
    body?: AdminCreateUserDto;
    path?: never;
    query?: never;
    url: '/api/admin/system/users';
};

export type PostApiAdminSystemUsersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTripsByTripIdData = {
    body?: never;
    path: {
        tripId: string;
    };
    query?: never;
    url: '/api/trips/{tripId}';
};

export type GetApiTripsByTripIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiTripsByTripIdError = GetApiTripsByTripIdErrors[keyof GetApiTripsByTripIdErrors];

export type GetApiTripsByTripIdResponses = {
    /**
     * OK
     */
    200: TripDetailDto;
};

export type GetApiTripsByTripIdResponse = GetApiTripsByTripIdResponses[keyof GetApiTripsByTripIdResponses];

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeResponses = {
    /**
     * OK
     */
    200: MeResponseDto;
};

export type GetApiUserMeResponse = GetApiUserMeResponses[keyof GetApiUserMeResponses];

export type GetApiUserMeTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me/tickets';
};

export type GetApiUserMeTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUserMeOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me/orders';
};

export type GetApiUserMeOrdersResponses = {
    /**
     * OK
     */
    200: unknown;
};
