// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pbl3.Data;

#nullable disable

namespace pbl3_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423221101_AddTripPoliciesFields")]
    partial class AddTripPoliciesFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "paid", "cancelled", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bus_admin_upgrade_request_status", new[] { "pending", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_status", new[] { "sent", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "email", "sms", "push" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_intent_status", new[] { "created", "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_provider", new[] { "momo", "stripe", "cash" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "refund_status", new[] { "pending", "processed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "seat_hold_status", new[] { "held", "confirmed", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "seat_type", new[] { "window", "aisle", "middle", "driver", "upper_deck", "lower_deck" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "station_type", new[] { "bus_station", "office", "pick_up_point" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_status", new[] { "issued", "checked_in", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_status", new[] { "scheduled", "running", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "passenger", "bus_admin", "sys_admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pbl3.Models.AdministrativeRegion", b =>
                {
                    b.Property<int>("AdministrativeRegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdministrativeRegionID"));

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<string>("CodeNameEn")
                        .HasColumnType("text")
                        .HasColumnName("code_name_en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.HasKey("AdministrativeRegionID");

                    b.ToTable("administrative_regions");
                });

            modelBuilder.Entity("Pbl3.Models.AdministrativeUnit", b =>
                {
                    b.Property<int>("AdministrativeUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdministrativeUnitID"));

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<string>("CodeNameEn")
                        .HasColumnType("text")
                        .HasColumnName("code_name_en");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("text")
                        .HasColumnName("full_name_en");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("ShortNameEn")
                        .HasColumnType("text")
                        .HasColumnName("short_name_en");

                    b.HasKey("AdministrativeUnitID");

                    b.ToTable("administrative_units");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("BookingID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.Property<Guid>("BusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusCompanyCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BusID");

                    b.HasIndex("BusCompanyCompanyID");

                    b.HasIndex("BusTypeID");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Pbl3.Models.BusAdminUpgradeRequest", b =>
                {
                    b.Property<Guid>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Hotline")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterUserID")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RequestID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ReviewedByUserID");

                    b.HasIndex("RequesterUserID", "Status", "RequestedAt");

                    b.ToTable("BusAdminUpgradeRequests");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompany", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hotline")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyID");

                    b.ToTable("BusCompanies");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompanyAdmin", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusCompanyCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("BusCompanyCompanyID");

                    b.ToTable("BusCompanyAdmins");
                });

            modelBuilder.Entity("Pbl3.Models.BusImage", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusID")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageID");

                    b.HasIndex("BusID");

                    b.ToTable("BusImages");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.Property<Guid>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalDistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("arrival_district_code");

                    b.Property<string>("ArrivalProvinceCode")
                        .HasColumnType("text")
                        .HasColumnName("arrival_province_code");

                    b.Property<string>("ArrivalWardCode")
                        .HasColumnType("text")
                        .HasColumnName("arrival_ward_code");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartureDistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("departure_district_code");

                    b.Property<string>("DepartureProvinceCode")
                        .HasColumnType("text")
                        .HasColumnName("departure_province_code");

                    b.Property<string>("DepartureWardCode")
                        .HasColumnType("text")
                        .HasColumnName("departure_ward_code");

                    b.Property<decimal>("DistanceEstimate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurationEstimate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteID");

                    b.HasIndex("CompanyID");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("Pbl3.Models.BusRouteStop", b =>
                {
                    b.Property<Guid>("BusRouteStopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationFromStart")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDropOff")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickUp")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationID")
                        .HasColumnType("uuid");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.HasKey("BusRouteStopID");

                    b.HasIndex("RouteID");

                    b.HasIndex("StationID");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("Pbl3.Models.BusType", b =>
                {
                    b.Property<Guid>("BusTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("BusTypeID");

                    b.ToTable("BusTypes");
                });

            modelBuilder.Entity("Pbl3.Models.District", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int?>("AdministrativeUnitID")
                        .HasColumnType("integer")
                        .HasColumnName("administrative_unit_id");

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("text")
                        .HasColumnName("full_name_en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("text")
                        .HasColumnName("province_code");

                    b.HasKey("Code");

                    b.HasIndex("AdministrativeUnitID");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("Pbl3.Models.Notification", b =>
                {
                    b.Property<Guid>("NotifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("NotifID");

                    b.HasIndex("BookingID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.Property<Guid>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("PassengerID");

                    b.HasIndex("UserID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.Property<Guid>("IntentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IntentID");

                    b.HasIndex("BookingID");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Pbl3.Models.Province", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int?>("AdministrativeRegionID")
                        .HasColumnType("integer")
                        .HasColumnName("administrative_region_id");

                    b.Property<int?>("AdministrativeUnitID")
                        .HasColumnType("integer")
                        .HasColumnName("administrative_unit_id");

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("text")
                        .HasColumnName("full_name_en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.HasKey("Code");

                    b.HasIndex("AdministrativeRegionID");

                    b.HasIndex("AdministrativeUnitID");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("Pbl3.Models.Refund", b =>
                {
                    b.Property<Guid>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntentID")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RefundID");

                    b.HasIndex("IntentID");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Pbl3.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("RatingScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewID");

                    b.HasIndex("BookingID");

                    b.HasIndex("TripID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Pbl3.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Pbl3.Models.SeatHold", b =>
                {
                    b.Property<Guid>("HoldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeatLayoutID")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionID")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("HoldID");

                    b.HasIndex("SeatLayoutID");

                    b.HasIndex("TripID");

                    b.HasIndex("UserID");

                    b.ToTable("SeatHolds");
                });

            modelBuilder.Entity("Pbl3.Models.SeatLayout", b =>
                {
                    b.Property<Guid>("LayoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<string>("SeatLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatType")
                        .HasColumnType("integer");

                    b.HasKey("LayoutID");

                    b.HasIndex("BusTypeID");

                    b.ToTable("SeatLayouts");
                });

            modelBuilder.Entity("Pbl3.Models.Station", b =>
                {
                    b.Property<Guid>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("district_code");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("text")
                        .HasColumnName("province_code");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WardCode")
                        .HasColumnType("text")
                        .HasColumnName("ward_code");

                    b.HasKey("StationID");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("ProvinceCode");

                    b.HasIndex("WardCode");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Pbl3.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PassengerID")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<Guid>("SeatLayoutID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.HasKey("TicketID");

                    b.HasIndex("BookingID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("SeatLayoutID");

                    b.HasIndex("TripID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.Property<Guid>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BusID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TripID");

                    b.HasIndex("BusID");

                    b.HasIndex("BusTypeID");

                    b.HasIndex("RouteID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pbl3.Models.Ward", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int?>("AdministrativeUnitID")
                        .HasColumnType("integer")
                        .HasColumnName("administrative_unit_id");

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<string>("DistrictCode")
                        .HasColumnType("text")
                        .HasColumnName("district_code");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("FullNameEn")
                        .HasColumnType("text")
                        .HasColumnName("full_name_en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.HasKey("Code");

                    b.HasIndex("AdministrativeUnitID");

                    b.HasIndex("DistrictCode");

                    b.ToTable("wards");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("Buses")
                        .HasForeignKey("BusCompanyCompanyID");

                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("Buses")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusCompany");

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Pbl3.Models.BusAdminUpgradeRequest", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("BusAdminUpgradeRequests")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.Models.User", "RequesterUser")
                        .WithMany("BusAdminUpgradeRequests")
                        .HasForeignKey("RequesterUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.User", "ReviewedByUser")
                        .WithMany("ReviewedBusAdminUpgradeRequests")
                        .HasForeignKey("ReviewedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusCompany");

                    b.Navigation("RequesterUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompanyAdmin", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("BusCompanyAdmins")
                        .HasForeignKey("BusCompanyCompanyID");

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("BusCompanyAdmins")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.BusImage", b =>
                {
                    b.HasOne("Pbl3.Models.Bus", "Bus")
                        .WithMany("BusImages")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("Routes")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusCompany");
                });

            modelBuilder.Entity("Pbl3.Models.BusRouteStop", b =>
                {
                    b.HasOne("Pbl3.Models.BusRoute", "Route")
                        .WithMany("BusRouteStops")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Station", "Station")
                        .WithMany("BusRouteStops")
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pbl3.Models.District", b =>
                {
                    b.HasOne("Pbl3.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany("Districts")
                        .HasForeignKey("AdministrativeUnitID");

                    b.HasOne("Pbl3.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceCode");

                    b.Navigation("AdministrativeUnit");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Pbl3.Models.Notification", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.Models.BusAdminUpgradeRequest", "Request")
                        .WithMany("Notifications")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Passengers")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("PaymentIntents")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Pbl3.Models.Province", b =>
                {
                    b.HasOne("Pbl3.Models.AdministrativeRegion", "AdministrativeRegion")
                        .WithMany("Provinces")
                        .HasForeignKey("AdministrativeRegionID");

                    b.HasOne("Pbl3.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany("Provinces")
                        .HasForeignKey("AdministrativeUnitID");

                    b.Navigation("AdministrativeRegion");

                    b.Navigation("AdministrativeUnit");
                });

            modelBuilder.Entity("Pbl3.Models.Refund", b =>
                {
                    b.HasOne("Pbl3.Models.PaymentIntent", "PaymentIntent")
                        .WithMany("Refunds")
                        .HasForeignKey("IntentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentIntent");
                });

            modelBuilder.Entity("Pbl3.Models.Review", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Pbl3.Models.SeatHold", b =>
                {
                    b.HasOne("Pbl3.Models.SeatLayout", "SeatLayout")
                        .WithMany()
                        .HasForeignKey("SeatLayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("SeatHolds")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("SeatHolds")
                        .HasForeignKey("UserID");

                    b.Navigation("SeatLayout");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.SeatLayout", b =>
                {
                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("SeatLayouts")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Pbl3.Models.Station", b =>
                {
                    b.HasOne("Pbl3.Models.District", "District")
                        .WithMany("Stations")
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.Models.Province", "Province")
                        .WithMany("Stations")
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.Models.Ward", "Ward")
                        .WithMany("Stations")
                        .HasForeignKey("WardCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("Pbl3.Models.Ticket", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.SeatLayout", "SeatLayout")
                        .WithMany()
                        .HasForeignKey("SeatLayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Passenger");

                    b.Navigation("SeatLayout");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.HasOne("Pbl3.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusID");

                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("Trips")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.BusRoute", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("BusType");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.HasOne("Pbl3.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pbl3.Models.Ward", b =>
                {
                    b.HasOne("Pbl3.Models.AdministrativeUnit", "AdministrativeUnit")
                        .WithMany("Wards")
                        .HasForeignKey("AdministrativeUnitID");

                    b.HasOne("Pbl3.Models.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictCode");

                    b.Navigation("AdministrativeUnit");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Pbl3.Models.AdministrativeRegion", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Pbl3.Models.AdministrativeUnit", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Provinces");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PaymentIntents");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.Navigation("BusImages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.BusAdminUpgradeRequest", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompany", b =>
                {
                    b.Navigation("BusAdminUpgradeRequests");

                    b.Navigation("BusCompanyAdmins");

                    b.Navigation("Buses");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.Navigation("BusRouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.BusType", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("SeatLayouts");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.District", b =>
                {
                    b.Navigation("Stations");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Pbl3.Models.Province", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Pbl3.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pbl3.Models.Station", b =>
                {
                    b.Navigation("BusRouteStops");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SeatHolds");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("BusAdminUpgradeRequests");

                    b.Navigation("BusCompanyAdmins");

                    b.Navigation("Notifications");

                    b.Navigation("Passengers");

                    b.Navigation("ReviewedBusAdminUpgradeRequests");

                    b.Navigation("SeatHolds");
                });

            modelBuilder.Entity("Pbl3.Models.Ward", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
