// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pbl3.Data;

#nullable disable

namespace pbl3_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225044255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "paid", "cancelled", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "calendar_exception_type", new[] { "added", "removed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_status", new[] { "sent", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "email", "sms", "push" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_charge_status", new[] { "captured", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_intent_status", new[] { "created", "succeeded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_provider", new[] { "momo", "stripe", "cash" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "refund_status", new[] { "pending", "processed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "seat_hold_status", new[] { "held", "confirmed", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "seat_type", new[] { "window", "aisle", "middle", "driver", "upper_deck", "lower_deck" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "station_type", new[] { "bus_station", "office", "pick_up_point" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_status", new[] { "issued", "checked_in", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_status", new[] { "scheduled", "running", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "passenger", "bus_admin", "sys_admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pbl3.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("BookingID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.Property<Guid>("BusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusCompanyCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BusID");

                    b.HasIndex("BusCompanyCompanyID");

                    b.HasIndex("BusTypeID");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompany", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hotline")
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyID");

                    b.ToTable("BusCompanies");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompanyAdmin", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusCompanyCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID");

                    b.HasIndex("BusCompanyCompanyID");

                    b.ToTable("BusCompanyAdmins");
                });

            modelBuilder.Entity("Pbl3.Models.BusImage", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusID")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageID");

                    b.HasIndex("BusID");

                    b.ToTable("BusImages");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.Property<Guid>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusCompanyCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DistanceEstimate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurationEstimate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteID");

                    b.HasIndex("BusCompanyCompanyID");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("Pbl3.Models.BusRouteStop", b =>
                {
                    b.Property<Guid>("BusRouteStopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationFromStart")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDropOff")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickUp")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationID")
                        .HasColumnType("uuid");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.HasKey("BusRouteStopID");

                    b.HasIndex("RouteID");

                    b.HasIndex("StationID");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("Pbl3.Models.BusType", b =>
                {
                    b.Property<Guid>("BusTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("BusTypeID");

                    b.ToTable("BusTypes");
                });

            modelBuilder.Entity("Pbl3.Models.Calendar", b =>
                {
                    b.Property<Guid>("CalendarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Fri")
                        .HasColumnType("boolean");

                    b.Property<bool>("Mon")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sat")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sun")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thu")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tue")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wed")
                        .HasColumnType("boolean");

                    b.HasKey("CalendarID");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Pbl3.Models.CalendarException", b =>
                {
                    b.Property<Guid>("ExceptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarID")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ExceptionID");

                    b.HasIndex("CalendarID");

                    b.ToTable("CalendarExceptions");
                });

            modelBuilder.Entity("Pbl3.Models.Notification", b =>
                {
                    b.Property<Guid>("NotifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("NotifID");

                    b.HasIndex("BookingID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.Property<Guid>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("PassengerID");

                    b.HasIndex("UserID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentCharge", b =>
                {
                    b.Property<Guid>("ChargeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntentID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentIntentIntentID")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderTxnID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ChargeID");

                    b.HasIndex("PaymentIntentIntentID");

                    b.ToTable("PaymentCharges");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.Property<Guid>("IntentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IntentID");

                    b.HasIndex("BookingID");

                    b.ToTable("PaymentIntents");
                });

            modelBuilder.Entity("Pbl3.Models.Permission", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("PermissionID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Pbl3.Models.Refund", b =>
                {
                    b.Property<Guid>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ChargeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaymentChargeChargeID")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RefundID");

                    b.HasIndex("PaymentChargeChargeID");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Pbl3.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("RatingScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewID");

                    b.HasIndex("BookingID");

                    b.HasIndex("TripID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Pbl3.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Pbl3.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uuid");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Pbl3.Models.SeatHold", b =>
                {
                    b.Property<Guid>("HoldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeatLayoutID")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionID")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("HoldID");

                    b.HasIndex("SeatLayoutID");

                    b.HasIndex("TripID");

                    b.HasIndex("UserID");

                    b.ToTable("SeatHolds");
                });

            modelBuilder.Entity("Pbl3.Models.SeatLayout", b =>
                {
                    b.Property<Guid>("LayoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<string>("SeatLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatType")
                        .HasColumnType("integer");

                    b.HasKey("LayoutID");

                    b.HasIndex("BusTypeID");

                    b.ToTable("SeatLayouts");
                });

            modelBuilder.Entity("Pbl3.Models.Station", b =>
                {
                    b.Property<Guid>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("StationID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Pbl3.Models.StopTime", b =>
                {
                    b.Property<Guid>("StopTimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StationID")
                        .HasColumnType("uuid");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.HasKey("StopTimeID");

                    b.HasIndex("StationID");

                    b.HasIndex("TripID");

                    b.ToTable("StopTimes");
                });

            modelBuilder.Entity("Pbl3.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PassengerID")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<Guid>("SeatLayoutID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uuid");

                    b.HasKey("TicketID");

                    b.HasIndex("BookingID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("SeatLayoutID");

                    b.HasIndex("TripID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.Property<Guid>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BusID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TripScheduleScheduleID")
                        .HasColumnType("uuid");

                    b.HasKey("TripID");

                    b.HasIndex("BusID");

                    b.HasIndex("BusTypeID");

                    b.HasIndex("RouteID");

                    b.HasIndex("TripScheduleScheduleID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.TripSchedule", b =>
                {
                    b.Property<Guid>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusTypeID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarID")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleID");

                    b.HasIndex("BusTypeID");

                    b.HasIndex("CalendarID");

                    b.HasIndex("RouteID");

                    b.ToTable("TripSchedules");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pbl3.Models.AuditLog", b =>
                {
                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("Buses")
                        .HasForeignKey("BusCompanyCompanyID");

                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("Buses")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusCompany");

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompanyAdmin", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("BusCompanyAdmins")
                        .HasForeignKey("BusCompanyCompanyID");

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("BusCompanyAdmins")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.BusImage", b =>
                {
                    b.HasOne("Pbl3.Models.Bus", "Bus")
                        .WithMany("BusImages")
                        .HasForeignKey("BusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.HasOne("Pbl3.Models.BusCompany", "BusCompany")
                        .WithMany("Routes")
                        .HasForeignKey("BusCompanyCompanyID");

                    b.Navigation("BusCompany");
                });

            modelBuilder.Entity("Pbl3.Models.BusRouteStop", b =>
                {
                    b.HasOne("Pbl3.Models.BusRoute", "Route")
                        .WithMany("BusRouteStops")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Station", "Station")
                        .WithMany("BusRouteStops")
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pbl3.Models.CalendarException", b =>
                {
                    b.HasOne("Pbl3.Models.Calendar", "Calendar")
                        .WithMany("CalendarExceptions")
                        .HasForeignKey("CalendarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Pbl3.Models.Notification", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("Passengers")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentCharge", b =>
                {
                    b.HasOne("Pbl3.Models.PaymentIntent", "PaymentIntent")
                        .WithMany("PaymentCharges")
                        .HasForeignKey("PaymentIntentIntentID");

                    b.Navigation("PaymentIntent");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("PaymentIntents")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Pbl3.Models.Refund", b =>
                {
                    b.HasOne("Pbl3.Models.PaymentCharge", "PaymentCharge")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentChargeChargeID");

                    b.Navigation("PaymentCharge");
                });

            modelBuilder.Entity("Pbl3.Models.Review", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Pbl3.Models.RolePermission", b =>
                {
                    b.HasOne("Pbl3.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pbl3.Models.SeatHold", b =>
                {
                    b.HasOne("Pbl3.Models.SeatLayout", "SeatLayout")
                        .WithMany()
                        .HasForeignKey("SeatLayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("SeatHolds")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.User", "User")
                        .WithMany("SeatHolds")
                        .HasForeignKey("UserID");

                    b.Navigation("SeatLayout");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pbl3.Models.SeatLayout", b =>
                {
                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("SeatLayouts")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusType");
                });

            modelBuilder.Entity("Pbl3.Models.StopTime", b =>
                {
                    b.HasOne("Pbl3.Models.Station", "Station")
                        .WithMany("StopTimes")
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Pbl3.Models.Ticket", b =>
                {
                    b.HasOne("Pbl3.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.SeatLayout", "SeatLayout")
                        .WithMany()
                        .HasForeignKey("SeatLayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Passenger");

                    b.Navigation("SeatLayout");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.HasOne("Pbl3.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusID");

                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("Trips")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.BusRoute", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.TripSchedule", "TripSchedule")
                        .WithMany("Trips")
                        .HasForeignKey("TripScheduleScheduleID");

                    b.Navigation("Bus");

                    b.Navigation("BusType");

                    b.Navigation("Route");

                    b.Navigation("TripSchedule");
                });

            modelBuilder.Entity("Pbl3.Models.TripSchedule", b =>
                {
                    b.HasOne("Pbl3.Models.BusType", "BusType")
                        .WithMany("TripSchedules")
                        .HasForeignKey("BusTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.Calendar", "Calendar")
                        .WithMany("TripSchedules")
                        .HasForeignKey("CalendarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.Models.BusRoute", "Route")
                        .WithMany("TripSchedules")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusType");

                    b.Navigation("Calendar");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.HasOne("Pbl3.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pbl3.Models.Booking", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PaymentIntents");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.Bus", b =>
                {
                    b.Navigation("BusImages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.BusCompany", b =>
                {
                    b.Navigation("BusCompanyAdmins");

                    b.Navigation("Buses");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Pbl3.Models.BusRoute", b =>
                {
                    b.Navigation("BusRouteStops");

                    b.Navigation("TripSchedules");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.BusType", b =>
                {
                    b.Navigation("Buses");

                    b.Navigation("SeatLayouts");

                    b.Navigation("TripSchedules");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.Calendar", b =>
                {
                    b.Navigation("CalendarExceptions");

                    b.Navigation("TripSchedules");
                });

            modelBuilder.Entity("Pbl3.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentCharge", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Pbl3.Models.PaymentIntent", b =>
                {
                    b.Navigation("PaymentCharges");
                });

            modelBuilder.Entity("Pbl3.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Pbl3.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pbl3.Models.Station", b =>
                {
                    b.Navigation("BusRouteStops");

                    b.Navigation("StopTimes");
                });

            modelBuilder.Entity("Pbl3.Models.Trip", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SeatHolds");

                    b.Navigation("StopTimes");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pbl3.Models.TripSchedule", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Pbl3.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bookings");

                    b.Navigation("BusCompanyAdmins");

                    b.Navigation("Notifications");

                    b.Navigation("Passengers");

                    b.Navigation("SeatHolds");
                });
#pragma warning restore 612, 618
        }
    }
}
